import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { 
  Sparkles, TrendingUp, HelpCircle, ArrowRight, Loader2, Play, RefreshCw, 
  CheckCircle, FileText, Calendar, Building, Landmark, Briefcase, Truck, Activity
} from 'lucide-react';
import { 
  ResponsiveContainer, AreaChart, Area, XAxis, YAxis, Tooltip, CartesianGrid, Legend 
} from 'recharts';

interface Insight {
  id: string;
  title: string;
  content: string;
  module: string;
  type: string;
  createdAt: string;
}

const AIInsights: React.FC = () => {
  const [insights, setInsights] = useState<Insight[]>([]);
  const [selectedModule, setSelectedModule] = useState<string>('EXECUTIVE');
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);

  // Simulated forecasting dataset
  const forecastData = [
    { name: 'Jan', actual: 4000, forecast: 4000 },
    { name: 'Feb', actual: 4500, forecast: 4400 },
    { name: 'Mar', actual: 5100, forecast: 4800 },
    { name: 'Apr', actual: 4900, forecast: 5100 },
    { name: 'May', actual: 5800, forecast: 5500 },
    { name: 'Jun', actual: 6200, forecast: 6000 },
    { name: 'Jul', actual: null, forecast: 6400 },
    { name: 'Aug', actual: null, forecast: 6700 },
    { name: 'Sep', actual: null, forecast: 7100 },
  ];

  const fetchInsights = async () => {
    setLoading(true);
    try {
      const res = await axios.get(`/api/ai/summary/${selectedModule}`);
      if (res.data?.data) {
        setInsights([res.data.data]);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchInsights();
  }, [selectedModule]);

  const handleGenerateCustom = async () => {
    setGenerating(true);
    try {
      const res = await axios.get(`/api/ai/summary/${selectedModule}`);
      if (res.data?.data) {
        setInsights([res.data.data]);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setGenerating(false);
    }
  };

  const parseMarkdown = (markdown: string) => {
    let html = markdown
      // Escape HTML tags to prevent XSS
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      // Headers
      .replace(/^### (.*$)/gim, '<h3 class="text-xs font-bold text-white mt-4 mb-2 flex items-center gap-1.5"><span class="w-1.5 h-1.5 rounded-full bg-indigo-500"></span>$1</h3>')
      // Bold
      .replace(/\*\*(.*?)\*\*/gim, '<strong class="text-white">$1</strong>');

    // Bullet items
    let lines = html.split('\n');
    lines = lines.map(line => {
      if (line.startsWith('* ') || line.startsWith('- ')) {
        return `<li class="ml-4 list-disc text-slate-300 text-[11px] mb-1.5">${line.slice(2)}</li>`;
      }
      return line;
    });

    return lines.join('\n');
  };

  const modules = [
    { name: 'Executive Overview', value: 'EXECUTIVE', icon: Activity },
    { name: 'Financial Ledger', value: 'FINANCE', icon: Landmark },
    { name: 'Human Resources', value: 'HR', icon: Briefcase },
    { name: 'Supply Chain SCM', value: 'SCM', icon: Truck },
    { name: 'CRM Pipeline', value: 'CRM', icon: Sparkles },
    { name: 'Project Delivery', value: 'PROJECT', icon: FileText },
  ];

  return (
    <div className="p-6 bg-slate-950 min-h-screen text-slate-100 space-y-6">
      
      {/* Title */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-900 pb-5">
        <div>
          <h1 className="text-xl font-bold text-white flex items-center gap-2">
            <Sparkles className="h-5.5 w-5.5 text-primary" />
            <span>AI Analytical Insights & KPI Trends</span>
          </h1>
          <p className="text-slate-400 text-xs mt-1">
            Generated by matching active SQL database nodes against statistical model projections.
          </p>
        </div>

        <button
          onClick={handleGenerateCustom}
          disabled={generating}
          className="flex items-center justify-center gap-2 px-3 py-2 bg-slate-800 hover:bg-slate-700 active:bg-slate-900 text-xs font-bold text-slate-100 rounded-lg border border-slate-700 shadow-sm transition-colors disabled:opacity-50"
        >
          {generating ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin text-slate-400" />
              <span>Scanning Database Ledger...</span>
            </>
          ) : (
            <>
              <RefreshCw className="h-3.5 w-3.5" />
              <span>Force Re-Analyze Ledger</span>
            </>
          )}
        </button>
      </div>

      {/* Module Filters Bar */}
      <div className="flex flex-wrap gap-2.5">
        {modules.map((m) => {
          const Icon = m.icon;
          return (
            <button
              key={m.value}
              onClick={() => setSelectedModule(m.value)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-semibold border transition-all duration-150 ${
                selectedModule === m.value
                  ? 'bg-indigo-600 border-indigo-500 text-white shadow-md'
                  : 'bg-slate-900/60 border-slate-800/80 text-slate-400 hover:text-slate-200 hover:bg-slate-900'
              }`}
            >
              <Icon className="h-4 w-4" />
              <span>{m.name}</span>
            </button>
          );
        })}
      </div>

      {/* Main Grid: Visuals & Narrative */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left 2 Columns: Insight Narrative & Forecast */}
        <div className="lg:col-span-2 space-y-6">
          
          {/* Narrative Insight Panel */}
          <div className="bg-slate-900/40 border border-slate-800 rounded-2xl p-6 relative overflow-hidden">
            <h3 className="text-xs uppercase tracking-wider text-slate-400 font-bold mb-4 flex items-center gap-1.5">
              <Activity className="h-4 w-4 text-indigo-400" />
              <span>Narrative Analytical Explanation</span>
            </h3>

            {loading ? (
              <div className="flex flex-col items-center justify-center py-20 text-slate-500 gap-2.5">
                <Loader2 className="h-6 w-6 animate-spin text-indigo-500" />
                <span className="text-xs">Parsing multi-tenant records...</span>
              </div>
            ) : insights.length === 0 ? (
              <div className="text-center py-20 text-xs text-slate-500">
                No insights parsed yet. Click Force Re-Analyze to trigger scanning.
              </div>
            ) : (
              insights.map((insight) => (
                <div key={insight.id} className="space-y-4">
                  <h2 className="text-base font-extrabold text-white">{insight.title}</h2>
                  <div 
                    className="space-y-2.5 leading-relaxed text-slate-300 text-xs border-t border-slate-900 pt-4" 
                    dangerouslySetInnerHTML={{ __html: parseMarkdown(insight.content) }} 
                  />
                  <div className="flex items-center gap-2 text-[10px] text-slate-500 font-medium bg-slate-950/60 p-3 rounded-lg border border-slate-900/60">
                    <Calendar className="h-3.5 w-3.5" />
                    <span>Run compiled on {new Date(insight.createdAt).toLocaleString()}</span>
                  </div>
                </div>
              ))
            )}
          </div>

          {/* Graphical Forecast Widget */}
          <div className="bg-slate-900/40 border border-slate-800 rounded-2xl p-6">
            <h3 className="text-xs uppercase tracking-wider text-slate-400 font-bold mb-4 flex items-center gap-1.5">
              <TrendingUp className="h-4 w-4 text-indigo-400" />
              <span>AI Trend Detection & Forecast Projection</span>
            </h3>
            
            <div className="h-64 w-full text-[10px] font-sans">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={forecastData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                  <defs>
                    <linearGradient id="colorActual" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.2}/>
                      <stop offset="95%" stopColor="#3b82f6" stopOpacity={0}/>
                    </linearGradient>
                    <linearGradient id="colorForecast" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#8b5cf6" stopOpacity={0.2}/>
                      <stop offset="95%" stopColor="#8b5cf6" stopOpacity={0}/>
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
                  <XAxis dataKey="name" stroke="#64748b" />
                  <YAxis stroke="#64748b" />
                  <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#1e293b', borderRadius: 8 }} />
                  <Legend iconSize={8} />
                  <Area type="monotone" dataKey="actual" name="Actual Performance" stroke="#3b82f6" strokeWidth={2} fillOpacity={1} fill="url(#colorActual)" />
                  <Area type="monotone" dataKey="forecast" name="AI Projected Trend" stroke="#8b5cf6" strokeWidth={2} strokeDasharray="5 5" fillOpacity={1} fill="url(#colorForecast)" />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>

        {/* Right 1 Column: Root Cause & Task Suggestions */}
        <div className="space-y-6">
          
          {/* Root Cause Analysis Card */}
          <div className="bg-slate-900/40 border border-slate-800 rounded-2xl p-6">
            <h3 className="text-xs uppercase tracking-wider text-slate-400 font-bold mb-4 flex items-center gap-1.5">
              <HelpCircle className="h-4 w-4 text-indigo-400" />
              <span>Root Cause Diagnosis</span>
            </h3>
            
            <div className="space-y-4 text-xs">
              <div className="border-l-2 border-amber-500 pl-3.5 space-y-1">
                <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wider">SCM Reorders Spike</span>
                <p className="text-slate-300 leading-normal">
                  Low stock restock warnings are driven by increased customer purchases on MacBook inventory products. Recommend updating reorder buffer limits.
                </p>
              </div>

              <div className="border-l-2 border-emerald-500 pl-3.5 space-y-1">
                <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wider">Cash reserves expansion</span>
                <p className="text-slate-300 leading-normal">
                  Cash runway healthy (9.4 months) due to positive invoice receipt reconciliations in Chase accounts.
                </p>
              </div>

              <div className="border-l-2 border-indigo-500 pl-3.5 space-y-1">
                <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wider">Workforce Stabilization</span>
                <p className="text-slate-300 leading-normal">
                  Low attrition rate (2.4%) maintained due to streamlined department transfers approved in HR console.
                </p>
              </div>
            </div>
          </div>

          {/* AI Task Suggestions */}
          <div className="bg-slate-900/40 border border-slate-800 rounded-2xl p-6">
            <h3 className="text-xs uppercase tracking-wider text-slate-400 font-bold mb-4 flex items-center gap-1.5">
              <Sparkles className="h-4 w-4 text-indigo-400" />
              <span>AI Task Action Proposals</span>
            </h3>

            <div className="space-y-2.5">
              {[
                'Issue RESTOCK purchase orders for MacBook SKU.',
                'Distribute payment overdue emails for Invoice INV-2026-004.',
                'Hold a performance check-in chat with Jessica Taylor.',
                'Reallocate engineering hours from pipeline backlogs.'
              ].map((taskText, idx) => (
                <div 
                  key={idx}
                  className="flex items-start gap-2.5 p-3 bg-slate-950/40 border border-slate-800/80 rounded-xl hover:border-slate-700 transition-colors cursor-pointer group"
                >
                  <CheckCircle className="h-4 w-4 text-slate-600 group-hover:text-indigo-400 transition-colors shrink-0 mt-0.5" />
                  <span className="text-xs text-slate-300 leading-snug group-hover:text-slate-100 transition-colors">{taskText}</span>
                </div>
              ))}
            </div>
          </div>

        </div>

      </div>

    </div>
  );
};

export default AIInsights;
export { AIInsights };
